version: '3'

services:
  envence-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ".:/usr/src/app"
      # - "/var/envence-media:/usr/src/app/public/"
    networks:
      - envence_network
      - envence_db_network
    depends_on:
      - envence-redis
      - envence-db
      - envence-rabbitmq

  envence-redis:
    container_name: "envence-redis"
    image: 'redis:latest'
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    volumes:
      - '/var/envence/redis:/data'
    networks:
      - envence_db_network

  # database containers, one for each db
  envence-fixPermissionsPostregres:
    image: 'bitnami/postgresql:14'
    user: root
    command: chown -R 1001:1001 /bitnami/postgresql
    volumes:
      - "/var/envence/pg:/bitnami/postgresql/data"

  envence-db:
    image: 'bitnami/postgresql:14'
    restart: always
    container_name: "envence-db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    volumes:
      - "/var/envence/pg:/bitnami/postgresql/data"
    ports:
      - "5432:5432"
    depends_on:
      - envence-fixPermissionsPostregres
    networks:
      - envence_db_network

  envence-rabbitmq:
    image: rabbitmq:3-management
    hostname: envence-rabbit
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      # - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      # - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - /var/envence/rabbitmq/data/:/var/lib/rabbitmq/
      - /var/envence/rabbitmq/logs/:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - envence_db_network

networks:
  envence_network:
    driver: bridge
  envence_db_network:
    driver: bridge
